#!/bin/sh

touch /etc/config/koti
uci set koti.dns=dns
uci set koti.dns.enable=1
uci add_list koti.dns.server=9.9.9.9
uci set koti.dnssec=dnssec
uci set koti.dnssec.enable=1
uci commit koti

return 0
