#!/bin/sh

uci -q delete ucitrack.@koti[-1] || true

touch /etc/config/koti
uci batch <<EOF
set koti.dnssec=dnssec
set koti.dnssec.enable=1
set koti.dot=dot
set koti.dot.enable=1
set koti.nts=nts
set koti.nts.enable=1
add_list koti.nts.server=nts.netnod.se
set koti.main=main
set koti.main.unbound_port=1053
add_list koti.dot.zone=fwd_quad9_dns
commit koti
EOF

return 0
