#!/bin/sh

touch /etc/config/koti
uci batch <<EOF
set koti.dnssec=dnssec
set koti.dnssec.enable=1
set koti.dot=dot
set koti.dot.enable=1
set koti.nts=nts
set koti.nts.enable=1
add_list koti.nts.server=nts.netnod.se
set koti.main=main
set koti.main.unbound_port=1053
add_list koti.dot.zone=fwd_quad9_dns
set koti.lan=iprange
set koti.lan.start=50
set koti.lan.limit=100
set koti.wg=iprange
set koti.wg.start=151
set koti.wg.limit=100
commit koti
EOF

return 0
