---
repos:
  - repo: local
    hooks:
      - id: shellcheck
        name: shellcheck
        language: system
        entry: shellcheck --external-sources
        types: [shell]
      - id: shfmt
        name: shfmt
        language: system
        entry: shfmt --indent 4 --diff --write
        types: [shell]
      - id: prettier
        name: prettier
        language: system
        entry: npm run prettier
        files: \.(vue|js|css|html|cjs|mjs|json)$
        pass_filenames: false
