#!/bin/sh

. /lib/functions.sh

koti_undo() {
    nft delete table inet koti 2>/dev/null || true
}

redirect_dns() {
    if test "$dot_enable" = 1; then
        redirect_port 53
    fi
}

redirect_port() {
    # https://en.wikipedia.org/wiki/Private_network
    local_networks="{ 127.0.0.0/8, 10.0.0.0/8, 172.16.0.0/12, 192.168.0.0/16 }"
    port="$1"
    nft -f- <<EOF
table inet koti {
    chain prerouting {
        type nat hook prerouting priority dstnat;
        policy accept;
        meta l4proto { udp, tcp } th dport $port ip daddr != $local_networks redirect to $port
    }
    #chain output {
    #    type nat hook output priority -100;
    #    policy accept;
    #    meta l4proto { udp, tcp } th dport $port ip daddr != $local_networks redirect to $port
    #}
}
EOF
}

dot() {
    case "$dot_enable" in
    1) printf "Enable DoT\n" >&2 ;;
    0) printf "Disable DoT\n" >&2 ;;
    esac
    config_load unbound
    config_foreach _disable_zone zone
    if test "$dot_enable" = 1; then
        config_load koti
        config_list_foreach dot zone _enable_zone
    fi
}

_disable_zone() {
    if expr "$1" : "fwd_.*$" >/dev/null; then
        printf "disable zone %s\n" "$1" >&2
        uci set unbound."$1".enabled=0
        uci set unbound."$1".fallback=0
    fi
}

_enable_zone() {
    printf "enable zone %s\n" "$1" >&2
    uci set unbound."$1".enabled=1
}

dnssec() {
    uci set unbound.ub_main.validator="$dnssec_enable"
    case "$dnssec_enable" in
    1) printf "Enable DNSSEC\n" >&2 ;;
    0) printf "Disable DNSSEC\n" >&2 ;;
    esac
}

nts() {
    if test "$nts_enable" = 1; then
        config_load koti
        while uci -q delete chrony.@pool[-1]; do true; done
        config_list_foreach nts server _add_nts_server
        uci set system.ntp.enabled=0
        redirect_port 123
    fi
    case "$nts_enable" in
    1) printf "Enable NTS\n" >&2 ;;
    0) printf "Disable NTS\n" >&2 ;;
    esac
}

_add_nts_server() {
    uci add chrony pool >/dev/null
    uci set chrony.@pool[-1].hostname="$1"
    uci set chrony.@pool[-1].iburst=1
    uci set chrony.@pool[-1].nts=1
}

backup_file() {
    if test -e "$1"; then
        cp -n "$1" "$(dirname "$1")"/."$(basename "$1")"-pre-koti
    fi
}

configure_dhcp() {
    backup_file /etc/config/dhcp
    domain="$(uci get dhcp.@dnsmasq[0].domain)"
    for server in $(uci get dhcp.@dnsmasq[0].server 2>/dev/null || true); do
        if ! expr "$server" : "/.*/.*" >/dev/null; then
            uci del_list dhcp.@dnsmasq[0].server="$server"
        fi
    done
    uci add_list dhcp.@dnsmasq[0].server="127.0.0.1#$unbound_port"
    uci add_list dhcp.@dnsmasq[0].server="::1#$unbound_port"
}

add_unbound_zone() {
    name="$1"
    tls_index="$2"
    server="$3"
    if ! uci -q get unbound."$name" >/dev/null; then
        uci batch <<EOF
set unbound.$name=zone
set unbound.$name.enabled=0
set unbound.$name.fallback=0
set unbound.$name.tls_index=$tls_index
set unbound.$name.tls_upstream=1
set unbound.$name.zone_type=forward_zone
add_list unbound.$name.zone_name=.
EOF
        for s in $server; do
            uci add_list unbound.$name.server=$s
        done
    fi
}

configure_unbound() {
    backup_file /etc/config/unbound
    add_unbound_zone fwd_quad9_dns dns.quad9.net \
        '9.9.9.9 149.112.112.112 2620:fe::fe 2620:fe::9'
    add_unbound_zone fwd_quad9_dns11 dns11.quad9.net \
        '9.9.9.11 149.112.112.11 2620:fe::11 2620:fe::fe:11'
    if test -n "$nextdns_id"; then
        add_unbound_zone fwd_nextdns "$nextdns_id.dns.nextdns.io" \
            '45.90.28.0 45.90.30.0 2a07:a8c0::0 2a07:a8c1::0'
    fi
    uci batch <<EOF
set unbound.ub_main.listen_port=$unbound_port
set unbound.ub_main.validator=1
set unbound.ub_main.add_local_fqdn=0
set unbound.ub_main.add_wan_fqdn=0
set unbound.ub_main.dhcp_link=none
set unbound.ub_main.domain=$domain
set unbound.ub_main.domain_type=refuse
EOF
}

change_config() {
    config="$1"
    changes="$(uci changes "$config")"
    uci commit "$config"
    if test -n "$changes"; then
        case "$config" in
        # no trigger
        chrony)
            if /etc/init.d/chronyd running; then
                /etc/init.d/chronyd restart
            fi
            ;;
        *)
            ubus call service event '{"type":"config.change","data":{"package":"'"$config"'"}}'
            ;;
        esac
    fi
}

set -e
config_load koti
config_get unbound_port main unbound_port 1053
config_get nextdns_id main nextdns_id
config_get dnssec_enable dnssec enable 1
config_get dot_enable dot enable 1
config_get nts_enable nts enable 1
koti_undo
redirect_dns
configure_unbound
dot
dnssec
nts
configure_dhcp
for config in dhcp unbound chrony system; do
    change_config "$config"
done
