#!/bin/sh /etc/rc.common

START=13
USE_PROCD=1

service_triggers() {
    procd_add_reload_trigger koti
}

start_service() {
    /usr/libexec/koti 2>&1 | logger -t koti -p daemon.info
}

reload_service() {
    start_service
}
