#!/bin/sh /etc/rc.common

START=99
USE_PROCD=1

service_triggers() {
    procd_add_reload_trigger koti
}

reload_service() {
    start
}

start_service() {
    procd_open_instance
    procd_set_param command /usr/libexec/koti
    procd_set_param stdout 1
    procd_set_param stderr 1
    procd_close_instance
}
